# Generated by Django 5.0.2 on 2024-02-22 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='expense_id',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payment_method',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='payment_method',
            name='id',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.DeleteModel(
            name='Payment_Method',
        ),
    ]
