# Generated by Django 5.0.2 on 2024-02-22 05:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='payment_method',
            old_name='id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expense_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
