# Generated by Django 5.0.2 on 2024-02-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rename_id_budget_user_rename_id_expenses_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
