# Generated by Django 5.0.2 on 2024-02-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_budget_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category_name',
            field=models.CharField(max_length=15),
        ),
    ]
