# Generated by Django 5.0.2 on 2024-02-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_expenses_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category_name',
            field=models.CharField(max_length=20),
        ),
    ]
