# Generated by Django 5.0.2 on 2024-02-22 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_expenses_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.expenses'),
        ),
    ]
