# Generated by Django 5.0.2 on 2024-02-22 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_budget_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='amount',
        ),
    ]
